---
name: bookly_app
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  get: ^4.6.5
  font_awesome_flutter: ^10.4.0
  flutter_svg: ^2.0.6
  google_fonts: ^4.0.5
  icons_flutter: ^0.0.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
flutter:
  uses-material-design: true
  assets:
  - Assets/Images/
  fonts:
  - family: Poppins
    fonts:
    - asset: Assets/Fonts/Poppins_Family/Poppins-Bold.ttf
