---
name: bookly_app
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  font_awesome_flutter: ^10.4.0
  flutter_svg: ^2.0.6
  google_fonts: ^4.0.4
  icons_flutter: ^0.0.4
  go_router: ^7.1.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  dio: ^5.1.2
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  cached_network_image: ^3.2.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
flutter:
  uses-material-design: true
  assets:
  - Assets/Images/
  fonts:
  - family: Poppins
    fonts:
    - asset: Assets/Fonts/Poppins_Family/Poppins-Bold.ttf
